export const DEFAULT_NODE_COLORS: Record<string, string> = {
  Document: '#1e40af',
  KnowledgeBase: '#4f46e5',
  Analysis: '#a21caf',
  Risk: '#dc2626',
  Milestone: '#16a34a',
  Technology: '#ea580c',
  Stakeholder: '#7c3aed',
  Topic: '#0891b2',
  Story: '#f59e0b',
  TestCase: '#ec4899',
  Epic: '#8b5cf6',
  Requirement: '#10b981',
  JiraIssue: '#3b82f6',
  Unknown: '#6b7280',
};

export const DEFAULT_NODE_LABELS_EN: Record<string, string> = {
  Document: 'Document',
  KnowledgeBase: 'Knowledge Base',
  Analysis: 'Analysis',
  Risk: 'Risk',
  Milestone: 'Milestone',
  Technology: 'Technology',
  Stakeholder: 'Stakeholder',
  Topic: 'Topic',
  Story: 'User Story',
  TestCase: 'Test Case',
  Epic: 'Epic',
  Requirement: 'Requirement',
  JiraIssue: 'Jira Issue',
  Unknown: 'Unknown',
};
