version: 1
disable_existing_loggers: false
formatters:
  structlog_formatter:
    format: '%(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: structlog_formatter
    stream: ext://sys.stdout
loggers:
  uvicorn:
    handlers: [console]
    level: INFO
    propagate: false
  uvicorn.error:
    level: INFO
  uvicorn.access:
    handlers: [console]
    level: WARNING
    propagate: false
root:
  level: INFO
  handlers: [console]
