// Demo property graph: customers, orders, products
CREATE
  (c1:Customer {id: 1, name: 'Alice Rossi',  country: 'IT'}),
  (c2:Customer {id: 2, name: 'Bob Bianchi',  country: 'IT'}),
  (c3:Customer {id: 3, name: 'Carla Verdi',  country: 'FR'}),
  (c4:Customer {id: 4, name: 'Dario Neri',   country: 'IT'}),
  (c5:Customer {id: 5, name: 'Eva Gialli',   country: 'DE'}),
  (p1:Product  {sku: 'SKU-001', title: 'Laptop 14"',     price: 1299.00}),
  (p2:Product  {sku: 'SKU-002', title: 'Wireless Mouse',   price: 29.90}),
  (p3:Product  {sku: 'SKU-003', title: 'Mechanical KB',   price: 149.00}),
  (p4:Product  {sku: 'SKU-004', title: 'USB-C Hub',        price: 59.00}),
  (p5:Product  {sku: 'SKU-005', title: '4K Monitor',      price: 449.00}),
  (o1:Order {id: 1, status: 'paid', total: 1299.00}),
  (o2:Order {id: 2, status: 'paid', total: 178.90}),
  (o3:Order {id: 3, status: 'paid', total: 449.00}),
  (o4:Order {id: 4, status: 'paid', total: 1299.00}),
  (o5:Order {id: 5, status: 'paid', total: 2598.00}),
  (c1)-[:PLACED]->(o1),
  (c1)-[:PLACED]->(o2),
  (c1)-[:PLACED]->(o3),
  (c2)-[:PLACED]->(o4),
  (c4)-[:PLACED]->(o5),
  (o1)-[:CONTAINS {qty: 1}]->(p1),
  (o2)-[:CONTAINS {qty: 1}]->(p2),
  (o2)-[:CONTAINS {qty: 1}]->(p3),
  (o3)-[:CONTAINS {qty: 1}]->(p5),
  (o4)-[:CONTAINS {qty: 1}]->(p1),
  (o5)-[:CONTAINS {qty: 2}]->(p1);
