//! Generated tonic stubs for the BaselithCore Red Agent endpoint daemon.
//!
//! The wire schema is owned by the BaselithCore monorepo
//! (`plugins/red_agent/proto/agent.proto`). This crate re-exports the
//! generated module under a stable path so downstream crates do not
//! depend on tonic's `include_proto!` location semantics.

#![deny(unsafe_code)]
#![warn(missing_docs)]

/// Generated module for the `baselith.red_agent.v1` proto package.
///
/// `missing_docs` is allowed inside this module because the source is
/// machine-generated by `tonic-build` and cannot carry per-field
/// rustdoc; the proto file is the documentation.
#[allow(missing_docs, clippy::all)]
pub mod v1 {
    tonic::include_proto!("baselith.red_agent.v1");
}

pub use v1::agent_channel_client::AgentChannelClient;
pub use v1::{
    AgentCapability, AgentHello, AgentMessage, Disconnect, Heartbeat, LogBatch, LogEntry, LogLevel,
    Platform, ServerHello, ServerMessage, Severity, TelemetryBatch, TelemetryEvent,
};

/// Server-side tonic stubs. Compiled only when the `server` feature
/// is enabled (test/dev builds). Production daemon binaries leave this
/// off so the binary footprint stays client-only.
#[cfg(feature = "server")]
pub use v1::agent_channel_server::{AgentChannel, AgentChannelServer};
