# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentChannelStub(object):
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    AgentChannel is the only RPC surface the daemon uses after enrollment.
    One bidirectional stream per agent, kept alive for the agent's lifetime.

    Authentication: mTLS 1.3 with ed25519 client cert. The server extracts
    `tenant_id` and `agent_uuid` from the SPIFFE-style URI SAN
    (`spiffe://baselith.io/tenant/{tenant_id}/agent/{agent_uuid}`) — never
    from message contents.

    Enrollment is a separate REST endpoint
    (`POST /red-agent/agents/enroll`) that issues the cert. See
    `plugins/red_agent/docs/agent_daemon.md` §6.3.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OpenStream = channel.stream_stream(
                '/baselith.red_agent.v1.AgentChannel/OpenStream',
                request_serializer=agent__pb2.AgentMessage.SerializeToString,
                response_deserializer=agent__pb2.ServerMessage.FromString,
                _registered_method=True)


class AgentChannelServicer(object):
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    AgentChannel is the only RPC surface the daemon uses after enrollment.
    One bidirectional stream per agent, kept alive for the agent's lifetime.

    Authentication: mTLS 1.3 with ed25519 client cert. The server extracts
    `tenant_id` and `agent_uuid` from the SPIFFE-style URI SAN
    (`spiffe://baselith.io/tenant/{tenant_id}/agent/{agent_uuid}`) — never
    from message contents.

    Enrollment is a separate REST endpoint
    (`POST /red-agent/agents/enroll`) that issues the cert. See
    `plugins/red_agent/docs/agent_daemon.md` §6.3.
    """

    def OpenStream(self, request_iterator, context):
        """Single bidirectional stream per agent. The method is named
        `OpenStream` (not `Connect`) because tonic auto-generates a
        transport-level `Client::connect()` constructor; a user RPC by
        the same name collides with that helper.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentChannelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OpenStream': grpc.stream_stream_rpc_method_handler(
                    servicer.OpenStream,
                    request_deserializer=agent__pb2.AgentMessage.FromString,
                    response_serializer=agent__pb2.ServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'baselith.red_agent.v1.AgentChannel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('baselith.red_agent.v1.AgentChannel', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentChannel(object):
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    AgentChannel is the only RPC surface the daemon uses after enrollment.
    One bidirectional stream per agent, kept alive for the agent's lifetime.

    Authentication: mTLS 1.3 with ed25519 client cert. The server extracts
    `tenant_id` and `agent_uuid` from the SPIFFE-style URI SAN
    (`spiffe://baselith.io/tenant/{tenant_id}/agent/{agent_uuid}`) — never
    from message contents.

    Enrollment is a separate REST endpoint
    (`POST /red-agent/agents/enroll`) that issues the cert. See
    `plugins/red_agent/docs/agent_daemon.md` §6.3.
    """

    @staticmethod
    def OpenStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/baselith.red_agent.v1.AgentChannel/OpenStream',
            agent__pb2.AgentMessage.SerializeToString,
            agent__pb2.ServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
