import { chromium } from 'playwright';
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
const errs = [];
page.on('console', m => { if (m.type() === 'error') errs.push(m.text()); });
page.on('pageerror', e => errs.push(`PAGE: ${e.message}`));
await page.goto('http://localhost:5174', { waitUntil: 'networkidle', timeout: 20000 });
console.log('TITLE', await page.title());
console.log('URL', page.url());
console.log('LOGIN_BTN', await page.locator('button:has-text("Login"), button:has-text("Accedi"), input[type=password]').count());
console.log('CHAT_INPUT', await page.locator('textarea, input[type=text]').count());
console.log('ERRS', JSON.stringify(errs, null, 2));
await page.screenshot({ path: '/tmp/probe-home.png', fullPage: false });
await browser.close();
