"""User files mixin for FilesystemInitializer."""


class UserFilesMixin:
    """Mixin providing _create_user_files method."""

    def _create_user_files(self) -> None:
        """Create realistic user home directory files."""
        home = f"/home/{self.username}"

        # Bash history with realistic commands
        self._create_file(
            f"{home}/.bash_history",
            """sudo apt update
sudo apt upgrade -y
cd /var/log
tail -f syslog
ps aux | grep nginx
systemctl status mysql
df -h
free -m
htop
cd ~
ls -la
cat /etc/passwd
netstat -tulpn
ss -tulpn
docker ps
# failed here, docker not installed
sudo apt install docker.io
# forgot sudo, trying again
history
vim /etc/nginx/nginx.conf
# q! to exit without saving
systemctl reload nginx
curl localhost
wget http://localhost/test
ping 8.8.8.8
traceroute google.com
nslookup google.com
dig google.com
ip a
ifconfig
route -n
cat /proc/cpuinfo
uname -a
uptime
who
w
last
""",
            permissions="rw-------",
        )

        # Comprehensive .bashrc
        self._create_file(
            f"{home}/.bashrc",
            """# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\\[\\033[01;32m\\]\\u@\\h\\[\\033[00m\\]:\\[\\033[01;34m\\]\\w\\[\\033[00m\\]\\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\\u@\\h:\\w\\$ '
fi

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\\''s/^\\s*[0-9]\\+\\s*//;s/[;&|]\\s*alert$//'\\'')"'

# enable programmable completion features
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
""",
            permissions="rw-r--r--",
        )

        # .profile
        self._create_file(
            f"{home}/.profile",
            """# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
""",
            permissions="rw-r--r--",
        )

        # SSH config
        self._create_file(
            f"{home}/.ssh/config",
            """# SSH client config

Host *
    ServerAliveInterval 60
    ServerAliveCountMax 3
    AddKeysToAgent yes
    IdentitiesOnly yes

# Example host
#Host myserver
#    HostName 192.168.1.100
#    User admin
#    Port 22
""",
            permissions="rw-------",
        )

        # SSH known hosts
        self._create_file(
            f"{home}/.ssh/known_hosts",
            """github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
gitlab.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp1Btn/nOeHHE5UOzRdf
""",
            permissions="rw-------",
        )

        # Viminfo
        self._create_file(
            f"{home}/.viminfo",
            """# This viminfo file was generated by Vim 8.1.
# You may edit it if you're careful!

# Viminfo version
|1,4

# Value of 'encoding' when this file was written
*encoding=utf-8

# hlsearch on (langstrings)
~h

# Command Line History (newest to oldest):
:q!
:wq
:w
:set number
:syntax on

# Search String History (newest to oldest):
?error
?password
?config

# Expression History (newest to oldest):

# Input Line History (newest to oldest):

# Debug Line History (newest to oldest):

# Registers:

# File marks:
'0  1  0  ~/.bashrc
'1  15  0  /etc/nginx/nginx.conf
'2  1  0  /var/log/syslog

# Jumplist (newest first):
-'  1  0  ~/.bashrc
-'  15  0  /etc/nginx/nginx.conf
""",
            permissions="rw-------",
        )

        # Less history
        self._create_file(
            f"{home}/.lesshst",
            """.less-history-file:
.search
"error"
"warning"
"fail"
""",
            permissions="rw-------",
        )

        # Old bashrc backup
        self._create_file(
            f"{home}/.bashrc.bak",
            "# old bashrc backup from migration\n",
            permissions="rw-r--r--",
        )

        # Downloads with notes
        self._create_file(
            f"{home}/Downloads/notes.txt",
            """server credentials:
- dev server: 192.168.1.50
- staging: check with ops team

TODO:
- finish migration script
- update SSL certs (expires march)
- clean up old logs
""",
            permissions="rw-r--r--",
        )
