"""CSS Part 3: tables, watermark, @page, footer."""

_PART3 = """
/* Improved Table Styling */
table {
    width: 100%;
    border-collapse: collapse;
    margin: 1em 0;
    font-size: 9.5pt;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.05);
}
th {
    background: linear-gradient(135deg, #1a1a2e, #16213e);
    color: white;
    font-weight: 600;
    padding: 10px 12px;
    text-align: left;
    font-size: 9pt;
    text-transform: uppercase;
    letter-spacing: 0.5px;
}
td {
    padding: 10px 12px;
    border-bottom: 1px solid #e9ecef;
}
tr:nth-child(even) {
    background: #f8f9fa;
}
tr:hover {
    background: #e9ecef;
}

/* Watermark */
.watermark {
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%) rotate(-45deg);
    font-size: 72pt;
    color: rgba(200, 200, 200, 0.08);
    pointer-events: none;
    z-index: -1;
    white-space: nowrap;
    font-weight: 800;
    letter-spacing: 10px;
}

/* Running Headers and Footers */
@page {
    @top-center {
        content: "CONFIDENTIAL - Security Intelligence Report";
        font-size: 8pt;
        color: #888;
        font-family: 'Helvetica Neue', Arial, sans-serif;
    }
    @bottom-left {
        content: "Report generated by Honeypot Research System";
        font-size: 7pt;
        color: #aaa;
    }
    @bottom-right {
        content: "Page " counter(page) " of " counter(pages);
        font-size: 8pt;
        color: #888;
    }
}
@page :first {
    @top-center {
        content: none;
    }
    @bottom-left {
        content: none;
    }
    @bottom-right {
        content: none;
    }
}
"""
